name: Deploy to GitHub Pages
permissions:
  contents: read  # 读取仓库内容权限
  id-token: write # OIDC 权限（关键）
  pages: write    # 部署 GitHub Pages 权限 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Setup pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install
 
    - name: Build
      run: pnpm run build
 
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./dist